quentin452 fixes (#19)
* Optimize worley algorythme + reduce tps lag caused by generation in nether

* Create fr_fr.lang

* BUMP VERSION

* apply plugin: maven-publish

fixes problems when using jitpack.io

* Increase performances during worldgen

- remove smooth chunks

-  reduce bottlenecks in plants/structures etc....

* remove makeBiomeArray multithreading

* fix crash when launching a world with this seed : 2465602432010453352

the issue was discovered in my modpack

crash report :

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=size, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 6 on block betternether:orange_mushroom, it is not an allowed value
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:14614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
    at gg.essential.loader.stage2.EssentialLoader.doInitialize(EssentialLoader.java:367)
    at gg.essential.loader.stage2.EssentialLoaderBase.initialize(EssentialLoaderBase.java:761)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gg.essential.loader.stage1.EssentialLoaderBase.initialize(EssentialLoaderBase.java:126)
    at gg.essential.loader.stage1.EssentialSetupTweaker.injectIntoClassLoader(EssentialSetupTweaker.java:59)
    at gg.essential.loader.stage0.EssentialSetupTweaker.injectIntoClassLoader(EssentialSetupTweaker.java:135)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=size, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 6 on block betternether:orange_mushroom, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:227)
    at paulevs.betternether.blocks.BlockOrangeMushroom.getStateFromMeta(BlockOrangeMushroom.java:74)
    at net.minecraft.block.Block.getStateById(Block.java:2736)
    at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnObject(NetHandlerPlayClient.java:437)
    at net.minecraft.network.play.server.SPacketSpawnObject.processPacket(SourceFile:124)
    at net.minecraft.network.play.server.SPacketSpawnObject.processPacket(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.redirect$zlk000$patcher$ignorePacketsFromClosedConnections(SourceFile:523)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 34 more

* fix #2

Fixed by changing entity name

* Make biomes more common + fix some small bugs

* Should fix #13 from official repo

https://github.com/Rebirth-of-the-Night/BetterNether/issues/13

* fix missing translation  + fix #12 from official repo

https://github.com/Rebirth-of-the-Night/BetterNether/issues/12

* Should fix #6 from official repo

https://github.com/Rebirth-of-the-Night/BetterNether/issues/6

* should fix #4 from official repo

https://github.com/Rebirth-of-the-Night/BetterNether/issues/4

* Some bug fix/hotfix/mistake fix

Fix Only 1 biome is generated around the world
readd smoothchunk , this function generate cities,,shoulrdn't be removed + optimize it
revert changes Make biomes more common
revert CityGenerator + BoundinBox + CityStructureManager changes to fix indexoutofbound

* Update build.gradle

* mini optimizations

* Quartz Stained Glass Pane names

* Update README.md

* Update README.md

* Bugfix + Enhancements

- MagmaFlower and BoneMushroom are now IGrowables (adds compat to RestrictedCrops mod)
- MagmaFlower now drops Magma Creams at the last growth stage

dupplicated :

https://github.com/michelegargiulo/BetterNether-Continuation/commit/0287cbb70d348c03145f2b54a6cf2d339e237675

* Fix compatibility with Restricted Crops

- Implemented Forge Hooks to check for proper CropGrow and SaplingGrow events

dupplicated :

https://github.com/michelegargiulo/BetterNether-Continuation/commit/77a9890e8b79ac31fbb555bb617db8ac511cf32a

---------

Co-authored-by: jbredwards <47703524+jbredwards@users.noreply.github.com>
Co-authored-by: H <37481947+H-QueerCoded@users.noreply.github.com>